---
title: "RAP cover vs biomass"
output: html_document
date: "`r lubridate::today()`"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Purpose compare rap biomass and cover for annuals and perennials
to see what the relationships exists.

## Dependencies

```{r message=FALSE, warning=FALSE}
library(tidyverse)
theme_set(theme_classic())
```


## Read in data

Data created in the RAP_cover_vs_biomass.js script.
These are a random sample of grid cells from within the sagebrush region

```{r}
df1 <- read_csv("data_processed/cover_vs_biomass/RAP_cover_and_biomass_mean_100000obs_30m_20221209.csv",
                show_col_types = FALSE) 
```


## Prepare data

```{r}
df2 <- df1 %>% 
  # the 'one' column was just a dummy variable
  select(-`system:index`, -.geo, -one)

# How many grid cells have all 0 values?
sum(df2$PFG == 0 & df2$AFG == 0 & df2$afgAGB==0 & df2$pfgAGB==0)

# rename columns
df3 <- df2 %>% 
  rename(afgCov = AFG, pfgCov = PFG)

# long form
df4 <- df3 %>% 
  mutate(id = 1:n()) %>% # this is the 'pixel number'
  pivot_longer(-id) %>% 
  mutate(pft = str_extract(name, "^[a-z]{3}"),
         pft = str_to_upper(pft),
         measure = str_extract(name, "[A-z]{3}$"),
         measure = case_when(measure == "Cov" ~ "Cover",
                             measure == "AGB" ~ "Biomass")) %>% 
  select(-name) %>% 
  pivot_wider(names_from = "measure",
              values_from = "value")
```

# Plot data

```{r message=FALSE, fig.width = 8, fig.height = 6}
g <- ggplot(df4, aes(Biomass, Cover)) +
  facet_wrap(~pft, scales = "free")

g  + geom_point(alpha = 0.5, size = 0.3)

g2 <- g  + geom_point(alpha = 0.05, size = 0.1)
g2 

g3 <- g2 + geom_smooth()
g3
g3 + geom_smooth(method = 'lm', color = 'darkgreen')


g + 
  geom_bin2d(bins = 50) +
  scale_fill_continuous(type = "viridis")
```

